name: Test the mex-utils library
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ github.token }}
      YARN_TOKEN: ${{ secrets.YARN_TOKEN }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
        with:
          node-version: '16.x'

      - name: Install Yarn
        run: npm install --location=global yarn

      - name: Install dependencies
        run: yarn install --network-timeout 1000000 --frozen-lockfile

      - name: Run tests for mex-utils
        env:
          NODE_OPTIONS: --experimental-vm-modules
        run: yarn nx run mex-utils:test
